- name: Install PyMySQL
  pip:
    name: PyMySQL

- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'


- name: Create MySQL extra databases 
  mysql_db:
    login_user: root
    login_password: '{{mysql_root_password}}'
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8mb4',true) }}"
    state: "{{ item.state | default('present',true) }}"
  with_items: "{{ mysql_databases }}"
  when: (mysql_databases is defined) and (mysql_databases != none)


- name: Create extra Databases User
  mysql_user:
    login_user: root
    login_password: '{{mysql_root_password}}'
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost',true) }}"
    password: "{{ item.password | default('123456',true) }}"
    priv: "{{ item.priv | default('*.*:USAGE',true) }}"
  with_items: "{{ mysql_users }}"
  when: (mysql_users is defined) and (mysql_users != none)


- name: Check MySQL Version
  shell: mysql -V
  register: mysql_ver
  notify: MySQL Version

#Enable remote connection
- import_tasks: remote.yml
  when: mysql_remote


